from typing import TypedDict


class _ResearchStateRequired(TypedDict):
    question: str
    kind: str                   # "research" | "conversational" — set by [classify]
    queries: list[str]          # planned by [plan], consumed by [search]
    search_results: list[dict]  # web results, accumulated across iterations
    kb_results: list[dict]      # KB results (empty if kb_search never called)
    reflections: list[str]      # gap notes from each [reflect] pass
    iteration: int              # guards against infinite loops
    final_answer: str | None


class ResearchState(_ResearchStateRequired, total=False):
    # Effort config — set by stream_graph() from the effort parameter
    max_iterations: int       # max reflect-loop iterations
    results_per_query: int    # max documents fetched per search call
    max_initial_queries: int  # max queries generated by plan node
    # Usage tracking — accumulated by search node
    searches_done: int
    links_evaluated: int
